# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bible_reference_parser}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nathan McWilliams"]
  s.date = %q{2010-09-29}
  s.description = %q{BibleReferenceParser can parse scriptures passages, such as 'Gen. 1:15-18, 21' to the individual books, chapters and verses in the passage. It also provides validation for invalid book names, chapters, and verses.}
  s.email = %q{nathan.mcwilliams@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".rspec",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bible_reference_parser.gemspec",
     "lib/bible_reference_parser.rb",
     "lib/bible_reference_parser/metadata/bible_metadata.rb",
     "lib/bible_reference_parser/metadata/metadata.yml",
     "lib/bible_reference_parser/parser.rb",
     "lib/bible_reference_parser/reference/behavior/tracks_errors.rb",
     "lib/bible_reference_parser/reference/book_reference.rb",
     "lib/bible_reference_parser/reference/chapter_reference.rb",
     "lib/bible_reference_parser/reference/reference_collection.rb",
     "lib/bible_reference_parser/reference/verse_reference.rb",
     "spec/bible_metadata_spec.rb",
     "spec/book_reference_spec.rb",
     "spec/chapter_reference_spec.rb",
     "spec/parser_spec.rb",
     "spec/reference_collection_spec.rb",
     "spec/shared/it_tracks_errors_shared.rb",
     "spec/spec_helper.rb",
     "spec/verse_reference_spec.rb"
  ]
  s.homepage = %q{http://github.com/endium/bible_reference_parser}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Parsing and validation for scripture passages.}
  s.test_files = [
    "spec/bible_metadata_spec.rb",
     "spec/book_reference_spec.rb",
     "spec/chapter_reference_spec.rb",
     "spec/parser_spec.rb",
     "spec/reference_collection_spec.rb",
     "spec/shared/it_tracks_errors_shared.rb",
     "spec/spec_helper.rb",
     "spec/verse_reference_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0.0.beta.19"])
      s.add_development_dependency(%q<simplecov>, [">= 0.3.2"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.0.beta.19"])
      s.add_dependency(%q<simplecov>, [">= 0.3.2"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.0.beta.19"])
    s.add_dependency(%q<simplecov>, [">= 0.3.2"])
  end
end

